# Generated by Django 5.1.1 on 2024-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ourservicesphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservicesphotos',
            name='photo',
            field=models.ImageField(upload_to='ourServicesPhotos'),
        ),
    ]
